version: '2.4'
services:
  postgres:
    image: postgres:11
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: patrician
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres

volumes:
  db_data: